name: deploy

on:
  workflow_call:


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
      - name: Install snaps
        run: |
          sudo snap install --classic charmcraft
          sudo snap install --classic concierge
          sudo snap install rabbitmq-perf-test
      - name: Prepare charm test environment
        run: |
          sudo concierge prepare -p k8s
      - name: Build Charm
        run: |
          sudo --user $(whoami) --preserve-env charmcraft -v pack
          mv rabbitmq-k8s*charm rabbitmq-k8s.charm
      - name: Run functional tests
        run: |
          uv run --with tox tox -e func-smoke -- --charm-file rabbitmq-k8s.charm
